### ISSUE TITLE
Проблема с форматом при чтении rudrec_annotated.json

### ISSUE THREAD

**Issue by aaselivanov** [cimm-kzn/RuDReC#3]
При попытке чтения файла rudrec_annotated.json посредством json.load возникает ошибка "JSONDecodeError: Extra data: line 2 column 1 (char 882)".

Похоже, что проблема с форматом сохранённого json: словари с отдельными твитами разделены "\n". 

Решил эту проблему следующим образом:
```
with open("../data/RuDREC/data/rudrec_annotated.json", "r") as raw_json_file:
    ann_raw_str = raw_json_file.read()

ann_raw_str = ann_raw_str.replace("}\n{","},{")
ann_raw_str = "[" + ann_raw_str + "]"
ann_list = json.loads(ann_raw_str)
```

Однако получившийся список содержит 4809 записи -- должно ли так быть?

**Comment by Ilseyar** [comment]
Здравствуйте!

В файле каждая строка является отдельным json-ом (соглашусь, формат json у файла не совсем верно обозначен). То есть правильно будет считывать файл построчно и конвертировать в json:

```
with open("dataset/rudrec_annotated.json") as raw_json_file:
    for line in raw_json_file:
        sentence = json.loads(line)
```

В каждом json-е хранится информация об одном предложении. Соответственно, 4809 - это кол-во предложений и оно верное.

**Comment by aaselivanov** [comment]
Спасибо за пояснение, теперь всё понятно!
